# Machine Learning Lab Evaluation

This lab includes two tasks: regression and classification. Each task compares three models: two traditional machine learning models and one neural network, with evaluations based on three metrics.

In [1]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from tensorflow.keras.utils import to_categorical
import pandas as pd
import numpy as np

## Task 1: Regression

### Step 1: Load Dataset
We use the Boston Housing dataset for the regression task.

Use Numpy library to import dataset.
<br>`numpy.load(FILE_PATH, allow_pickle=True).item()`
<br>The dataset structure is dictionary-format.

In [2]:
# Load the data
FILE_PATH = 'boston-dataset.npy'
data = np.load(FILE_PATH, allow_pickle=True).item()
data

# -------------------------------
# Your code here
# -------------------------------

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]], shape=(506, 13)),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
    

In [3]:
# Show 3 samples of dataset
print("Features")
print(data['data'][:3])
print()
print("Target")
print(data['target'][:3])
# -------------------------------
# Your code here
# -------------------------------

Features
[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]]

Target
[24.  21.6 34.7]


### Step 2: Split and Scale Data
We split the dataset into training and testing sets, then standardize the features for better performance.

In [4]:
# Split the data using train_test_split function
# 80% of the data will be used for training and 20% for testing
# Random state is set to 42
X = data['data']
y = data['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# -------------------------------
# Your code here
# -------------------------------

# Standardize the data
# Use StandardScaler to standardize the data
# Use fit_transform method on the training data and transform method on the testing data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -------------------------------
# Your code here
# -------------------------------

In [5]:
# Show variable shape
print("Variable shape")
print("X_train >>", X_train.shape)
print("X_test >>", X_test.shape)
print("y_train >>", y_train.shape)
print("y_test >>", y_test.shape)
# -------------------------------
# Your code here
# -------------------------------

Variable shape
X_train >> (404, 13)
X_test >> (102, 13)
y_train >> (404,)
y_test >> (102,)


### Step 3: Train Models
We train three models: Linear Regression, Random Forest Regressor, and a Neural Network.
<br>Steps: 
1) Import/Build the model, 
2) Fit the model, 
3) Predict the target values.

In [6]:
# Linear Regression
# Create a Linear Regression model
# -------------------------------
# Your code here
# -------------------------------
model = LinearRegression()

# Fit the model
# -------------------------------
# Your code here
# -------------------------------
model.fit(X_train, y_train)

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------
y_pred = model.predict(X_test)

In [7]:
# Random Forest Regressor
# Use RandomForestRegressor to train the model with random_state=42
# -------------------------------
# Your code here
# -------------------------------
rf_model = RandomForestRegressor(random_state=42)

# Fit the model
# -------------------------------
# Your code here
# -------------------------------
rf_model.fit(X_train, y_train)


# Predict the target values
# -------------------------------
# Your code here
# -------------------------------
y_pred_rf = rf_model.predict(X_test)

In [8]:
# Neural Network
# Create a neural network model with 2 hidden layers with 64 units and ReLU activation function

nn_model_reg = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(1)
])

# Compile the model with adam optimizer and mean squared error loss function
# -------------------------------
# Your code here
# -------------------------------
nn_model_reg.compile(optimizer='adam', loss='mse')

# Fit the model with 50 epochs and batch size of 16
# -------------------------------
# Your code here
# -------------------------------
nn_model_reg.fit(X_train, y_train, epochs=50, batch_size=16)

# Predict the target values using the model
# -------------------------------
# Your code here
# -------------------------------
y_pred_nn = nn_model_reg.predict(X_test)

C:\Users\Acer\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 568.8218
Epoch 2/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 435.8048
Epoch 3/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 232.2625
Epoch 4/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 78.1829
Epoch 5/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 44.3614
Epoch 6/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.9018
Epoch 7/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.4860
Epoch 8/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.0573
Epoch 9/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.5623
Epoch 10/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.9278
Epoch 11/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.8585
Epoch 12/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.8630
Epoch 13/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.9319
Epoch 14/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.2962
Epoch 15/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.8505
E

### Step 4: Evaluate Models
We evaluate the models using Mean Squared Error (MSE), Mean Absolute Error (MAE), and R² Score.

In [9]:
# Evaluate the models
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

mse_rf = mean_squared_error(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

mse_nn = mean_squared_error(y_test, y_pred_nn)
mae_nn = mean_absolute_error(y_test, y_pred_nn)
r2_nn = r2_score(y_test, y_pred_nn)

print("Regression Task:")
print("Linear Regression:")
print(f"MSE: {mse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"R2 Score: {r2:.4f}")
print()
print("Random Forest Regressor:")
print(f"MSE: {mse_rf:.4f}")
print(f"MAE: {mae_rf:.4f}")
print(f"R2 Score: {r2_rf:.4f}")
print()
print("Neural Network:")
print(f"MSE: {mse_nn:.4f}")
print(f"MAE: {mae_nn:.4f}")
print(f"R2 Score: {r2_nn:.4f}")


# -------------------------------
# Your code here
# -------------------------------

Regression Task:
Linear Regression:
MSE: 24.2911
MAE: 3.1891
R2 Score: 0.6688

Random Forest Regressor:
MSE: 7.9127
MAE: 2.0411
R2 Score: 0.8921

Neural Network:
MSE: 12.3424
MAE: 2.2974
R2 Score: 0.8317


---
---
---

## Task 2: Classification

### Step 1: Load Dataset
We use the Iris dataset for the classification task.

In [10]:
# Load the data
# -------------------------------
# Your code here
# -------------------------------
df = pd.read_csv('iris_dataset.csv')

# Show the first 5 rows of the dataset
# -------------------------------
# Your code here
# -------------------------------
df.head()

,sepal_length,sepal_width,petal_length,petal_width,target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [11]:
# Split the data into features and target
# -------------------------------
# Your code here
# -------------------------------
X = df.drop('target', axis=1)
y = df['target']


In [12]:
# Show 3 samples of features
# -------------------------------
# Your code here
# -------------------------------
print("Features")
print(X.values[:3])
print()
print("Target")
print(y.values[:3])

Features
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

Target
[0 0 0]


### Step 2: Split and Scale Data
We split the dataset into training and testing sets, then standardize the features for better performance.

In [13]:
# Split the data using train_test_split function
# 80% of the data will be used for training and 20% for testing
# Random state is set to 42
# -------------------------------
# Your code here
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
# Use StandardScaler to standardize the data
# Use fit_transform method on the training data and transform method on the testing data
# -------------------------------
# Your code here
# -------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Step 2.5: Encode Target Variable
We encode the target variable using One-Hot Encoding.

In [14]:
# One-hot encode for neural network
# -------------------------------
# Your code here
# -------------------------------
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [15]:
# Show variable shape
# -------------------------------
# Your code here
# -------------------------------
print("Variable shape")
print("X_train >>", X_train.shape)
print("y_train >>", y_train.shape)
print("X_test >>", X_test.shape)
print("y_test >>", y_test.shape)

Variable shape
X_train >> (120, 4)
y_train >> (120, 3)
X_test >> (30, 4)
y_test >> (30, 3)


### Step 3: Train Models
We train three models: Logistic Regression, Random Forest Classifier, and a Neural Network.
<br>Steps: 
1) Import/Build the model, 
2) Fit the model, 
3) Predict the target values.

In [16]:
# Logistic Regression
# Create a Logistic Regression model
# -------------------------------
# Your code here
# -------------------------------
lr_model = LogisticRegression()

# Fit the model
# -------------------------------
lr_model.fit(X_train, np.argmax(y_train, axis=1))

# Predict the target values
# -------------------------------
y_pred_lr = lr_model.predict(X_test)

In [17]:
# Random Forest Classifier
# Use RandomForestClassifier to train the model with random_state=42
# -------------------------------
# Your code here
# -------------------------------
rf_model_clf = RandomForestClassifier(random_state=42)

# Fit the model
# -------------------------------
rf_model_clf.fit(X_train, y_train)

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------
y_pred_rf_clf = rf_model_clf.predict(X_test)

In [18]:
# Neural Network
# Create a neural network model with 2 hidden layers with 64 units and ReLU activation function
nn_model_cls = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(y_train.shape[1], activation='softmax')
])

# Compile the model with adam optimizer and categorical crossentropy loss function
# Use accuracy as the metric
# -------------------------------
# Your code here
# -------------------------------
nn_model_cls.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Fit the model with 50 epochs and batch size of 16
# -------------------------------
# Your code here
# -------------------------------
nn_model_cls.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test))

# Predict the target values using the model
# Use argmax to get the predicted class
# -------------------------------
# Your code here
# -------------------------------
y_pred_nn = nn_model_cls.predict(X_test)
y_pred_nn = np.argmax(y_pred_nn, axis=1)

Epoch 1/50


C:\Users\Acer\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.4333 - loss: 1.0526 - val_accuracy: 0.8667 - val_loss: 0.9052
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8250 - loss: 0.8398 - val_accuracy: 0.9000 - val_loss: 0.7076
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8333 - loss: 0.6646 - val_accuracy: 0.9000 - val_loss: 0.5358
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8250 - loss: 0.5281 - val_accuracy: 0.8667 - val_loss: 0.4142
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8167 - loss: 0.4358 - val_accuracy: 0.9000 - val_loss: 0.3396
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8167 - loss: 0.3755 - val_accuracy: 0.9000 - val_loss: 0.2870
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8417 - loss: 0.3325 - val_accuracy: 0.9000 - val_loss: 0.2455
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8500 - loss: 0.2996 - val_accuracy: 0.9333 - val_loss: 0.2155
Epoch 9/50


### Step 4: Evaluate Models
We evaluate the models using Accuracy, Precision, and Recall.

In [19]:
# Evaluate the models
# -------------------------------
# Your code here
# -------------------------------
y_test_1d = np.argmax(y_test, axis=1)
y_pred_rf_1d = np.argmax(y_pred_rf_clf, axis=1)

print("Classification Task:")
print("Logistic Regression:")
print("Accuracy:", f"{accuracy_score(y_test_1d, y_pred_lr):.4f}")
print("Precision:", f"{precision_score(y_test_1d, y_pred_lr, average='weighted'):.4f}")
print("Recall:", f"{recall_score(y_test_1d, y_pred_lr, average='weighted'):.4f}")
print("F1 Score:", f"{f1_score(y_test_1d, y_pred_lr, average='weighted'):.4f}")
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test_1d, y_pred_lr))
print()
print("Random Forest Classifier:")
print("Accuracy:", f"{accuracy_score(y_test_1d, y_pred_rf_1d):.4f}")
print("Precision:", f"{precision_score(y_test_1d, y_pred_rf_1d, average='weighted'):.4f}")
print("Recall:", f"{recall_score(y_test_1d, y_pred_rf_1d, average='weighted'):.4f}")
print("F1 Score:", f"{f1_score(y_test_1d, y_pred_rf_1d, average='weighted'):.4f}")
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test_1d, y_pred_rf_1d))
print()
print("Neural Network:")
print("Accuracy:", f"{accuracy_score(y_test_1d, y_pred_nn):.4f}")
print("Precision:", f"{precision_score(y_test_1d, y_pred_nn, average='weighted'):.4f}")
print("Recall:", f"{recall_score(y_test_1d, y_pred_nn, average='weighted'):.4f}")
print("F1 Score:", f"{f1_score(y_test_1d, y_pred_nn, average='weighted'):.4f}")
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test_1d, y_pred_nn))

Classification Task:
Logistic Regression:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Random Forest Classifier:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Neural Network:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
