# Machine Learning Lab Evaluation

This lab includes two tasks: regression and classification. Each task compares three models: two traditional machine learning models and one neural network, with evaluations based on three metrics.

In [83]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from tensorflow.keras.utils import to_categorical
import pandas as pd
import numpy as np

## Task 1: Regression

### Step 1: Load Dataset
We use the Boston Housing dataset for the regression task.

Use Numpy library to import dataset.
<br>`numpy.load(FILE_PATH, allow_pickle=True).item()`
<br>The dataset structure is dictionary-format.

In [84]:
# Load the data

# -------------------------------
# Your code here
# -------------------------------

In [85]:
# Show 3 samples of dataset

# -------------------------------
# Your code here
# -------------------------------

Features
[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]]

Target
[24.  21.6 34.7]


### Step 2: Split and Scale Data
We split the dataset into training and testing sets, then standardize the features for better performance.

In [86]:
# Split the data using train_test_split function
# 80% of the data will be used for training and 20% for testing
# Random state is set to 42

# -------------------------------
# Your code here
# -------------------------------

# Standardize the data
# Use StandardScaler to standardize the data
# Use fit_transform method on the training data and transform method on the testing data

# -------------------------------
# Your code here
# -------------------------------

In [87]:
# Show variable shape

# -------------------------------
# Your code here
# -------------------------------

Variable shape
X_train >> (404, 13)
y_train >> (102, 13)
X_test >> (404,)
y_test >> (102,)


### Step 3: Train Models
We train three models: Linear Regression, Random Forest Regressor, and a Neural Network.
<br>Steps: 
1) Import/Build the model, 
2) Fit the model, 
3) Predict the target values.

In [88]:
# Linear Regression
# Create a Linear Regression model
# -------------------------------
# Your code here
# -------------------------------


# Fit the model
# -------------------------------
# Your code here
# -------------------------------


# Predict the target values
# -------------------------------
# Your code here
# -------------------------------

In [89]:
# Random Forest Regressor
# Use RandomForestRegressor to train the model with random_state=42
# -------------------------------
# Your code here
# -------------------------------

# Fit the model
# -------------------------------
# Your code here
# -------------------------------

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------

In [90]:
# Neural Network
# Create a neural network model with 2 hidden layers with 64 units and ReLU activation function

nn_model_reg = Sequential([
    Dense(..., activation=..., input_shape=(...,)),
    Dense(..., activation=...),
    Dense(...)
])

# Compile the model with adam optimizer and mean squared error loss function
# -------------------------------
# Your code here
# -------------------------------

# Fit the model with 50 epochs and batch size of 16
# -------------------------------
# Your code here
# -------------------------------

# Predict the target values using the model
# -------------------------------
# Your code here
# -------------------------------

4/4 [==============================] - 0s 1ms/step


### Step 4: Evaluate Models
We evaluate the models using Mean Squared Error (MSE), Mean Absolute Error (MAE), and R² Score.

In [91]:
# Evaluate the models

# -------------------------------
# Your code here
# -------------------------------

Regression Task:
Linear Regression:
  MSE: 24.2911
  MAE: 3.1891
  R2 Score: 0.6688

Random Forest Regressor:
  MSE: 7.9127
  MAE: 2.0411
  R2 Score: 0.8921

Neural Network:
  MSE: 12.0683
  MAE: 2.3187
  R2 Score: 0.8354



---
---
---

## Task 2: Classification

### Step 1: Load Dataset
We use the Iris dataset for the classification task.

In [92]:
# Load the data
# -------------------------------
# Your code here
# -------------------------------

# Show the first 5 rows of the dataset
# -------------------------------
# Your code here
# -------------------------------

,sepal_length,sepal_width,petal_length,petal_width,target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [93]:
# Split the data into features and target
# -------------------------------
# Your code here
# -------------------------------

In [94]:
# Show 3 samples of features
# -------------------------------
# Your code here
# -------------------------------

Features
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

Target
[0 0 0]


### Step 2: Split and Scale Data
We split the dataset into training and testing sets, then standardize the features for better performance.

In [95]:
# Split the data using train_test_split function
# 80% of the data will be used for training and 20% for testing
# Random state is set to 42
# -------------------------------
# Your code here
# -------------------------------

# Standardize the data
# Use StandardScaler to standardize the data
# Use fit_transform method on the training data and transform method on the testing data
# -------------------------------
# Your code here
# -------------------------------

### Step 2.5: Encode Target Variable
We encode the target variable using One-Hot Encoding.

In [96]:
# One-hot encode for neural network
# -------------------------------
# Your code here
# -------------------------------

In [97]:
# Show variable shape
# -------------------------------
# Your code here
# -------------------------------

Variable shape
X_train >> (120, 4)
y_train >> (120, 3)
X_test >> (30, 4)
y_test >> (30, 3)


### Step 3: Train Models
We train three models: Logistic Regression, Random Forest Classifier, and a Neural Network.
<br>Steps: 
1) Import/Build the model, 
2) Fit the model, 
3) Predict the target values.

In [ ]:
# Logistic Regression
# Create a Logistic Regression model
# -------------------------------
# Your code here
# -------------------------------

# Fit the model
# -------------------------------
# Your code here
# -------------------------------

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------

In [99]:
# Random Forest Classifier
# Use RandomForestClassifier to train the model with random_state=42
# -------------------------------
# Your code here
# -------------------------------

# Fit the model
# -------------------------------
# Your code here
# -------------------------------

# Predict the target values
# -------------------------------
# Your code here
# -------------------------------

In [100]:
# Neural Network
# Create a neural network model with 2 hidden layers with 64 units and ReLU activation function
nn_model_cls = Sequential([
    Dense(..., activation=..., input_shape=(...,)),
    Dense(..., activation=...),
    Dense(..., activation=...)
])

# Compile the model with adam optimizer and categorical crossentropy loss function
# Use accuracy as the metric
# -------------------------------
# Your code here
# -------------------------------

# Fit the model with 50 epochs and batch size of 16
# -------------------------------
# Your code here
# -------------------------------

# Predict the target values using the model
# Use argmax to get the predicted class
# -------------------------------
# Your code here
# -------------------------------

1/1 [==============================] - 0s 35ms/step


### Step 4: Evaluate Models
We evaluate the models using Accuracy, Precision, and Recall.

In [101]:
# Evaluate the models
# -------------------------------
# Your code here
# -------------------------------

Classification Task:
Logistic Regression:
  Accuracy: 1.0000
  Precision: 1.0000
  Recall: 1.0000
  F1 Score: 1.0000

 Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Random Forest Classifier:
  Accuracy: 1.0000
  Precision: 1.0000
  Recall: 1.0000
  F1 Score: 1.0000

 Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Neural Network:
  Accuracy: 1.0000
  Precision: 1.0000
  Recall: 1.0000
  F1 Score: 1.0000

 Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

